services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: kak
      POSTGRES_PASSWORD: kak
      POSTGRES_DB: kak
    ports:
      - "5432:5432"
    volumes:
      - kak_dev_pg:/var/lib/postgresql/data

  piper:
    build: ./piper
    environment:
      PIPER_VOICE: id_ID-news_tts-medium
    ports:
      - "5001:5000"
    volumes:
      - piper_data:/data

volumes:
  kak_dev_pg:
  piper_data:
